# Generated by Django 4.2.3 on 2023-07-31 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
    ]
