# Generated by Django 4.2.3 on 2023-08-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_search_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.AddField(
            model_name='search',
            name='user_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
