# Generated by Django 4.2.3 on 2023-08-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
