# Generated by Django 4.2.3 on 2023-08-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(),
        ),
    ]
