# Generated by Django 4.2.3 on 2023-07-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="country",),
    ]
