# Generated by Django 4.2.3 on 2023-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("published_at", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "articles",},
        ),
    ]
