# Generated by Django 4.2.3 on 2023-07-25 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("brieflyai", "0002_rename_text_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="search", name="text", field=models.TextField(max_length=500),
        ),
    ]
