# Generated by Django 4.2.3 on 2023-07-25 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brieflyai", "0003_search_time_alter_search_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="search", name="text",),
        migrations.RemoveField(model_name="search", name="time",),
        migrations.AddField(
            model_name="search",
            name="query",
            field=models.CharField(default="test", max_length=255),
        ),
        migrations.AddField(
            model_name="search",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 25, 17, 53, 25, 363684, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="search",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
